---
title: Organized Wonder
url: http://www.organizedwonder.com
timezone: America/New_York
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: video
    thumbnail: "/assets/images/thumb-placeholder.png"
    source: ""
    html: ""
exclude:
- tmp
- ".gitignore"
- node_modules/
- bower_components/
- package.json
- webpack.config.js
- Gemfile
gems:
  - jekyll-paginate
paginate: 30
paginate_path: "/videos/page/:num/"