---
title: Organized Wonder
url: http://www.organizedwonder.com
timezone: America/New_York
collections:
  users:
    title: Users
    output: true
  tags:
    title: Tags
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: video
    thumbnail: "/assets/images/thumb-placeholder.png"
    source: ""
    html: ""
- scope:
    path: ''
    type: users
  values:
    layout: user
    twitter: ""
- scope:
    path: ''
    type: tags
  values:
    layout: tag
    videos: []
exclude:
- tmp
- ".gitignore"
- node_modules/
- bower_components/
- package.json
- webpack.config.js
- Gemfile
gems:
  - jekyll-paginate
paginate: 30
paginate_path: "/videos/page/:num/"